### ISSUE TITLE
Installation problem，cannot find nvcc

### ISSUE THREAD

**Issue by KatnissD** [Danko-Lab/Rgtsvm#11]
When I installed Rgtsvm, the nvcc file of the CUDA library could not be found, but nvcc is indeed in usr/bin. I even can't install it with root privileges，what should I do?

**Comment by wzhy2000** [comment]
Did you check the install part in the vignette? (Page2)
https://github.com/Danko-Lab/Rgtsvm/blob/master/Rgtsvm-vignette.pdf

**Comment by KatnissD** [comment]
I tried it,but  the bash prompt is: module: command not found. Forgive me for being a newcomer to getting started. I only use python and perl. It is very difficult for me to write a module with c++ script. 
    I am actually trying your dREG. When I run run_dREG.bsh, I can't find the Rgtsvm package. Now I want try online dREG, thank you.
