### ISSUE TITLE
svm cross fold error

### ISSUE THREAD

**Issue by ivanvishnu** [Danko-Lab/Rgtsvm#14]
Hi, 
I'm getting an error while training svm with cross=5, whereas svm works for the same data with cross=0. Please let me know if you any suggestions to fix it.
library(Rgtsvm)
BigMatX <- attach.bigmatrix(bigmemory::as.matrix(trainGenoNewTableComb))
dim(BigMatX)
[1] 3200 4289
length(trainPheno)
[1] 3200
folds=5
model1<- (svm(x=BigMatX,y=trainPheno,kernel="radial",type="eps-regression",cross=folds,probability=FALSE,verbose=FALSE,no.change.x=TRUE)) 
Error in base::":"(from, to) : argument of length 0

thanks,
Vishnu

**Comment by wzhy2000** [comment]
I Submitted new codes to solve this problem. Please try again, Thanks.
