### ISSUE TITLE
Error while predicting Multi-Class with class.weights set

### ISSUE THREAD

**Issue by AlexanderSchmedes** [Danko-Lab/Rgtsvm#2]
Hello,

first of all thanks for creating this package. It's incredibly fast and very helpful!

I started experimenting with it the last few days and it worked fine until I started using class.weights. My data has 3 classes (-1, 0, 1) and 80% of all data is in class 0. Setting the weights like this (just examples):

`class.weights = c("-1" = 0.1, "0" = 0.8, "-1" = 0.1) or
class.weights = c(0.1, 0.8, 0.1) or
class.weights = c(1,8,1)
`

works fine while training, but when I use the predict function I get this error:

> Error in gtsvmpredict.classfication.call(newdata, sparse, object, param,  : 
  NA/NaN/Inf in foreign function call (arg 14)

It works using class.weights like 

`class.weights = c("-1" = 1, "0" = 1, "-1" = 1) or
class.weights = c(0.1, 0.1, 0.1) or
class.weights = c(1,1,1)
`

so as long as they are all the same it works, but I don't know if it just ignores class.weights anyway if they are all the same.

I saw the test files so I can just guess that class.weights and multi-class work as long as they are not used together.

Thanks in advance!

**Comment by wzhy2000** [comment]
I can't reproduce this problem. Do you have any data to share with me?

**Comment by wzhy2000** [comment]
I reproduced your problem and fixed it. Thank you for your finding.

**Comment by AlexanderSchmedes** [comment]
Oh, I'm sorry I somehow missed the notification of you answering. That's great to hear! Thank you very much!
