### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by nevenus** [Danko-Lab/Rgtsvm#4]
I have problem in executing built R package. 
I build Rgtsvm using cuda 8.0 and boost 1.55 (also try 1.65) libraries. I successfully load Rgtsvm in R.
then after:
library(Rgtsvm)
data("iris")
model <- Rgtsvm::svm(Species ~ ., data = iris) 
I get this error:
terminate called after throwing an instance of 'GTSVM::CUDA::Exception'
  what():  svm.cpp:738: Failed to allocate space for found keys on host (unknown error)
Aborted (core dumped)

Any advice? Thanks

**Comment by wzhy2000** [comment]
I met the similar problem couple months ago. Finally we found the CUDA driver didn't match the CUDA library used for compile. So you can check this point at first.
