### ISSUE TITLE
cannot find GPU

### ISSUE THREAD

**Issue by Spamiad** [Danko-Lab/Rgtsvm#8]
Hi,
when using the getGPU function I receive '0'. It should find a K80.
Can this be an issue with the installation or did something else go wrong?

**Comment by wzhy2000** [comment]
You mean getGPUcount()?
The return values indicate how many GPU cards can be identified by CUDA library( Function: cudaGetDeviceCount)

**Comment by Spamiad** [comment]
Yes, I've compiled Rgtsvm with SM_30 but it cannot find any of the K80 GPUs.
