### ISSUE TITLE
Error: SparseKernelFindLargestPositiveGradient

### ISSUE THREAD

**Issue by beibeiJ** [Danko-Lab/Rgtsvm#9]
Dear Rgtsvm author,

I am a new user of Rgtisvm and not familiar with the following error:
Error: SparseKernelFindLargestPositiveGradient: did not find the desired number of maxima[1] "Error in GPU process."

Do you have any idea that what this error could come from? My data,  cuda, or something else?

**Comment by ppolo23** [comment]
I'm having the same issue. Did you found any solution?

**Comment by ppolo23** [comment]
I'm having the same issue. 
Did you found any solution?

**Comment by ppolo23** [comment]
I'm trying the following:
svm_iris<- Rgtsvm::svm(Species ~ ., data=iris)
and the error is:
**Error: SparseKernelFindLargestScore: did not find the desired number of maximaError in gtsvmtrain.classfication.call(y, x, param, verbose = verbose) : Error in GPU process.**

**Comment by wzhy2000** [comment]
I tried your examples many times and didn't reproduce your error. Can you tell me your CUDA version and R information?

I have tested on CUDA 8.0.

**Comment by ppolo23** [comment]
I'm using 

- CUDA 8.0:
_nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61_

- R 3.6.0:
_R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)_

- Boost 1.70.0

All of them over Ubuntu 16.04.

**Comment by wzhy2000** [comment]
Would you like to try R 3.4.2?

**Comment by wzhy2000** [comment]
I got your email that you mentioned your GPU is NVIDIA GeForce GT 730. If this GPU, please try SM_30 as the CUDA arch. 

Change line 2382 in Rgtsvm/Rgtsvm/configure.
and line 30 in Rgtsvm/Rgtsvm/configure.ac

Check this post:
http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

Please let me know whether it works for you.

**Comment by ppolo23** [comment]
That completely solved my problem!! It worked for R 3.6.
Thank you very much!

**Comment by wzhy2000** [comment]
add a new option --with-cuda-arch for the installation command.
